server:
  port: 8090

spring:
  application:
    name: shop-web-feign-user

feign:
  hystrix:
    enabled: true

eureka:
  #eureka服务端的实例名称
  hostname: 127.0.0.1
  client:
    service‐url:
      defaultZone: http://127.0.0.1:8001/eureka/