server:
  port: 9090

spring:
  application:
    name: shop-web-ribbon-user

eureka:
  #eureka服务端的实例名称
  hostname: 127.0.0.1
  client:
    service‐url:
      defaultZone: http://127.0.0.1:8001/eureka/